-- Run this entire file in Supabase Dashboard > SQL Editor.
-- Activity history starts from the moment this migration is installed.

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text,
  actor_email text,
  action text not null check (
    action in (
      'request_created',
      'status_changed',
      'request_archived',
      'request_restored',
      'request_deleted',
      'request_auto_deleted',
      'department_created',
      'user_created',
      'user_updated'
    )
  ),
  entity_type text not null check (
    entity_type in ('request', 'department', 'user')
  ),
  entity_id uuid,
  request_id uuid references public.it_requests(id) on delete set null,
  request_code text,
  description text not null check (char_length(description) between 1 and 500),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx
  on public.activity_logs (created_at desc);

create index if not exists activity_logs_action_created_idx
  on public.activity_logs (action, created_at desc);

create index if not exists activity_logs_request_idx
  on public.activity_logs (request_id, created_at desc)
  where request_id is not null;

alter table public.activity_logs enable row level security;

drop policy if exists "Admins can view activity logs"
  on public.activity_logs;
create policy "Admins can view activity logs"
on public.activity_logs for select
to authenticated
using (private.is_admin());

revoke all on table public.activity_logs from anon, authenticated;
grant select on table public.activity_logs to authenticated;

create or replace function private.log_it_request_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_actor_id uuid := auth.uid();
  current_actor_name text;
  current_actor_email text;
  status_label text;
begin
  select profile.full_name, profile.email
  into current_actor_name, current_actor_email
  from public.profiles as profile
  where profile.id = current_actor_id;

  if tg_op = 'INSERT' then
    insert into public.activity_logs (
      actor_id,
      actor_name,
      actor_email,
      action,
      entity_type,
      entity_id,
      request_id,
      request_code,
      description,
      metadata
    )
    values (
      current_actor_id,
      current_actor_name,
      current_actor_email,
      'request_created',
      'request',
      new.id,
      new.id,
      new.code,
      'สร้างคำขอ “' || left(new.subject, 350) || '”',
      jsonb_build_object(
        'department', new.department,
        'priority', new.priority,
        'requester_name', new.requester_name
      )
    );

    return new;
  end if;

  if old.status is distinct from new.status then
    status_label := case new.status
      when 'waiting' then 'รอรับเรื่อง'
      when 'in_progress' then 'กำลังดำเนินการ'
      when 'done' then 'เสร็จสิ้น'
      else new.status
    end;

    insert into public.activity_logs (
      actor_id,
      actor_name,
      actor_email,
      action,
      entity_type,
      entity_id,
      request_id,
      request_code,
      description,
      metadata
    )
    values (
      current_actor_id,
      current_actor_name,
      current_actor_email,
      'status_changed',
      'request',
      new.id,
      new.id,
      new.code,
      'เปลี่ยนสถานะเป็น “' || status_label || '”',
      jsonb_build_object(
        'old_status', old.status,
        'new_status', new.status,
        'subject', new.subject
      )
    );
  end if;

  if old.archived_at is null and new.archived_at is not null then
    insert into public.activity_logs (
      actor_id,
      actor_name,
      actor_email,
      action,
      entity_type,
      entity_id,
      request_id,
      request_code,
      description,
      metadata
    )
    values (
      current_actor_id,
      current_actor_name,
      current_actor_email,
      'request_archived',
      'request',
      new.id,
      new.id,
      new.code,
      'ย้ายคำขอไปยังคลังสำรอง',
      jsonb_build_object('subject', new.subject)
    );
  elsif old.archived_at is not null and new.archived_at is null then
    insert into public.activity_logs (
      actor_id,
      actor_name,
      actor_email,
      action,
      entity_type,
      entity_id,
      request_id,
      request_code,
      description,
      metadata
    )
    values (
      current_actor_id,
      current_actor_name,
      current_actor_email,
      'request_restored',
      'request',
      new.id,
      new.id,
      new.code,
      'กู้คืนคำขอจากคลังสำรอง',
      jsonb_build_object('subject', new.subject)
    );
  end if;

  return new;
end;
$$;

create or replace function private.log_department_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_actor_id uuid := auth.uid();
  current_actor_name text;
  current_actor_email text;
begin
  select profile.full_name, profile.email
  into current_actor_name, current_actor_email
  from public.profiles as profile
  where profile.id = current_actor_id;

  insert into public.activity_logs (
    actor_id,
    actor_name,
    actor_email,
    action,
    entity_type,
    entity_id,
    description,
    metadata
  )
  values (
    current_actor_id,
    current_actor_name,
    current_actor_email,
    'department_created',
    'department',
    new.id,
    'เพิ่มแผนก “' || new.name || '”',
    jsonb_build_object('department_name', new.name)
  );

  return new;
end;
$$;

revoke all on function private.log_it_request_activity() from public;
revoke all on function private.log_department_activity() from public;

drop trigger if exists log_it_request_activity on public.it_requests;
create trigger log_it_request_activity
after insert or update of status, archived_at on public.it_requests
for each row execute function private.log_it_request_activity();

drop trigger if exists log_department_activity on public.departments;
create trigger log_department_activity
after insert on public.departments
for each row execute function private.log_department_activity();

-- Push newly-created history items into the Admin history page.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'activity_logs'
  ) then
    alter publication supabase_realtime
      add table public.activity_logs;
  end if;
end
$$;
